# Generated by Django 5.2.6 on 2026-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='generation',
            name='generate_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='ratio',
            field=models.CharField(default='16:9', max_length=10),
        ),
        migrations.AddField(
            model_name='generation',
            name='reference_audio',
            field=models.FileField(blank=True, null=True, upload_to='references/audio/'),
        ),
        migrations.AddField(
            model_name='generation',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to='references/images/'),
        ),
        migrations.AddField(
            model_name='generation',
            name='reference_video',
            field=models.FileField(blank=True, null=True, upload_to='references/videos/'),
        ),
        migrations.AddField(
            model_name='generation',
            name='watermark',
            field=models.BooleanField(default=False),
        ),
    ]
