# Generated by Django 5.2.6 on 2026-09-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_generation_duration_generation_generate_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='reference_audio',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='reference_image',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='reference_video',
        ),
        migrations.CreateModel(
            name='ReferenceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='references/multi/')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_media', to='generations.generation')),
            ],
        ),
    ]
