# Generated by Django 5.2.6 on 2026-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_remove_generation_reference_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='resolution',
            field=models.CharField(default='720p', max_length=20),
        ),
    ]
