# Generated by Django 5.2.6 on 2026-09-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0005_chatsession_generation_chat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
