# Generated by Django 5.2.6 on 2026-09-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0006_chatsession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='resolution',
            field=models.CharField(default='480p', max_length=20),
        ),
    ]
