# Generated by Django 5.2.6 on 2026-09-15 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0007_alter_generation_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Auto', 'Auto'), ('Character', 'Character'), ('Location', 'Location'), ('Prop', 'Prop')], default='Auto', max_length=50)),
                ('workspace', models.CharField(default='Default', max_length=100)),
                ('media_file', models.FileField(upload_to='uploads/elements/')),
                ('byteplus_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('byteplus_asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('byteplus_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/raw/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
