# Generated by Django 5.2.6 on 2026-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0008_element_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='byteplus_asset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='byteplus_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='byteplus_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='Untitled Upload', max_length=200),
        ),
    ]
