# Generated by Django 5.2.6 on 2026-09-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0009_upload_byteplus_asset_id_upload_byteplus_group_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
