# Generated by Django 5.2.6 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0010_delete_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemedia',
            name='byteplus_asset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
