# Generated by Django 5.2.6 on 2026-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0011_referencemedia_byteplus_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
