# Generated by Django 5.2.6 on 2026-09-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0012_generation_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
