# Generated by Django 5.2.6 on 2026-09-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0013_generation_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
